### ISSUE TITLE
Manage SSL Certificates with Let's Encrypt

### ISSUE THREAD

**Issue by vialcollet** [RocketChat/Rocket.Chat.Ansible#17]
Hi and thanks a lot for this great role.
I have manage to handle let's encrypt. I am a beginner with Ansible so let me know what you think of the approach and I can submit a pull request if you want.
The main issue is that we need a valid nginx configuration (with valid certificates) in order to use the webroot validation.

My approach is the following (we should add a variable to activate this):
- Adjust the nginx configuration template
- Let RocketChat role generating self-signed certificates. 
- Then I use a role from thefinn93 (https://github.com/thefinn93/ansible-letsencrypt) to install Let's Encrypt, request the certificate and setup the automatic renewal. 
- Then I delete the self-signed certificates and symlink Let's Encrypt certificates.

Changes in rocket_chat.conf.j2 (in the ssl server section):

``` NGINX
 location ~ /.well-known { 

 root /var/www/letsencrypt;
 allow all;                
 }                         
```

Then my playbook:

``` YAML

---
  - name: Apply the RocketChat.Server role to all chat_servers
    vars:
      rocket_chat_automatic_upgrades: true
      rocket_chat_tarball_sha256sum: 316673b6e11993b32f0499ef3a28316f3780d23a7c5a756f07211edaa727b982
      letsencrypt_webroot_path: /var/www/letsencrypt
      letsencrypt_email: my@email.com
      # letsencrypt_server: https://acme-staging.api.letsencrypt.org/directory
      letsencrypt_server: https://acme-v01.api.letsencrypt.org/directory
      rocket_chat_ssl_generate_certs: true
    hosts: chat_servers
    pre_tasks:
      - name: Create let's encrypt root folder
        file: path=/var/www/letsencrypt state=directory mode=0775
    roles:
      - RocketChat.Server
      - letsencrypt
    tasks:
      - name: Delete self-signed certificates
        file: path={{ item }} state=absent
        with_items:
        - '{{rocket_chat_ssl_key_path }}'
        - '{{ rocket_chat_ssl_cert_path }}'
      - name: "symlink to Let's Encrypt key: {{rocket_chat_ssl_key_path }}"
        file: src='/etc/letsencrypt/live/{{ ansible_fqdn }}/privkey.pem' dest={{ rocket_chat_ssl_key_path }} state=link
      - name: "Symlink to Let's Encrypt certificate: {{ rocket_chat_ssl_cert_path }}"
        file: src='/etc/letsencrypt/live/{{ ansible_fqdn }}/fullchain.pem' dest={{ rocket_chat_ssl_cert_path }} state=link
        notify: Reload the Nginx service
```

**Comment by cmacrae** [comment]
Hi again @vialcollet :wave:

Awesome, this is good to hear - this is something I've been wanting to implement for a while.
I should get some time to go over this properly today, bit busy at the moment, but I have some initial thoughts about this:

Due to the flexibility of the role, and the different services it deploys, it cannot depend on other roles.
So far, I've written it in such a way that it supports deployment of the necessary services at what could be considered a "basic" level. User's have the option to either use this role's basic deployment of said services, or if they desire more fine-grained/sophisticated control of a service, they can opt out of this role deploying the service with a simple variable setting, then use another role to manage it.

I'd like to take the same approach with Let's Encrypt, being that I would implement my own code for the deployment, and expose a variable that allows user's to stick with my deployment code, or use another role.

Considering you've been kind enough to share this with me - I'd like to ask you, as a user, what your thoughts would be on the above? This is really the approach I'd like to take, but I'll value any insight you may have on the matter :)

**Comment by vialcollet** [comment]
Hi @cmacrae 

I really like your approach. I know there is a lot of debate around whether ansible roles should be highly specialized on a services or cover a full solution. In the case of Let's Encrypt you might also want to setup a cron job for the renewal.
My (recent) experience on this is related to... sensu stack installation :) And I have to say that the work you have done in this area is absolutely fantastic. I am using it myself! So once you understand the role and its variables you can very quickly deploy your stack. Much more than if you have to interface roles to build the solution. With the sensu example, I am still trying to get graphite and grafana into the picture for example...
So I would encourage you to go in this direction.
This being said I have seen a role with nice integration of the Let's Encrypt role from Thefinn93. I used it to deploy a JitsuMeet server. You can check here: 
Here is my resulting playbook with his role:
```YAML
- name: Configure jitsi-meet server.
  hosts: jitsi_servers
  vars:
    # Change this to match the DNS entry for your host IP.
    jitsi_meet_server_name: '{{ ansible_fqdn }}'
  roles:
    - role: letsencrypt
      become: yes
      letsencrypt_email: "admin@my-server.fr"
      letsencrypt_cert_domains:
        - "{{ jitsi_meet_server_name }}"
      tags: letsencrypt

    - role: freedomofpress.jitsi-meet
      jitsi_meet_ssl_cert_path: "/etc/letsencrypt/live/{{ jitsi_meet_server_name }}/fullchain.pem"
      jitsi_meet_ssl_key_path: "/etc/letsencrypt/live/{{ jitsi_meet_server_name }}/privkey.pem"
      become: yes
      tags: jitsi
```

What do you think?
I am happy to dig further with you. But don't forget I am an Ansible beginner (happy beginner though).
