### ISSUE TITLE
checksum mismatch on Rocket.Chat binary tarball

### ISSUE THREAD

**Issue by nate8199** [RocketChat/Rocket.Chat.Ansible#29]
not sure what I should do about this one

`TASK [RocketChat.Server : Fetch the Rocket.Chat binary tarball] ****************
fatal: [rocket]: FAILED! => {"changed": false, "failed": true, "msg": "The checksum for /var/lib/rocket.chat/rocket.chat-latest.tgz did not match 024671fabd9dce34149affe27b0e20e967a7209e94358e5771ae81d2a9a5f477; it was e001895f4319f34b0bc6d68af03ced3ac32a6715d98ffcab88f7d89b44ae4f98."}
`

@xenithorb  thank you for explaining multiple solutions.

**Comment by xenithorb** [comment]
Firstly, please understand that the idea here is to maintain the integrity and security of the upgrade by cryptographically ensuring that the hash of what the playbook expects, matches what it downloads.

The "ansible way" for dealing with playbook versions is to do something called _version pinning_, which basically means that if you ask for `version: v2.0`  you get exactly the same version (of code) of the playbook every time.  Bear in the mind that in order to use the latest tag, you must not specify a `version: ` OR you can specify `version: master` for the bleeding-edge. (In your requirements file to be used with `ansible-galaxy`)

----

There are three ways to handle this situation:

1. Wait for the Rocket.Chat.Ansible team to make a new commit and update the hash. Then with `ansible-galaxy install -f -r <requirements_file>.yml` upgrade the playbook directly from ansible galaxy. 

2.  In your playbook, override the default hash by writing something like:
  ```yaml
  - hosts: servers
    roles:
      - role: RocketChat.Server
        rocket_chat_tarball_sha256sum: <the_updated_sha256_sum>
  ```

  You may calculate the sha256sum by using the following commands:

  ```bash
  # Both of these commands will work, choose one:
  curl -Ls https://rocket.chat/releases/latest/download | sha256sum

  # The wget method
  wget -O - https://rocket.chat/releases/latest/download | sha256sum

  ```

  For example, the current hash is `e001895f4319f34b0bc6d68af03ced3ac32a6715d98ffcab88f7d89b44ae4f98` which has been updated in https://github.com/RocketChat/Rocket.Chat.Ansible/commit/81f0f8cc7d18592b977d3c74123ca085827c8177

3.  In version 2 of the playbook I added a feature, mostly for testing suites like Vagrant and Travis-CI, (that is, the build would fail for other code changes if the the version was bumped by Rocket.Chat), to skip the checksum check if one desired to do an _"insecure upgrade."_ See: https://github.com/RocketChat/Rocket.Chat.Ansible/commit/5e86223eb512e2844feb698103d539a94626888e

  ```yaml
  - hosts: servers
    roles:
      - role: RocketChat.Server
        #rocket_chat_tarball_sha256sum: <the_updated_sha256_sum>
        rocket_chat_tarball_check_checksum: false 
  ```

  This is set to `true` by default for obvious reasons, but may be overridden if you prefer to not check the integrity of the tarball during the running of the playbook.

---

##### Note: If doing an upgrade, don't forget to also set `rocket_chat_automatic_upgrades` to `true`.
