### ISSUE TITLE
Add localhost binding in /etc/hosts

### ISSUE THREAD

**Issue by k-c-p** [RocketChat/Rocket.Chat.Ansible#35]
The roles adds an entry in `/etc/hosts` that links 127.0.0.1 to the hostname and server-FQDN. Something like:
```
127.0.0.1    server.fqdn    server.hostname
```

As a consequence there is no entry for `localhost` in `/etc/hosts` which may affect services that rely on this. Suggestion is to adopt the role that the entry in `/etc/hosts` includes `localhost` and looks like this:
```
127.0.0.1    server.fqdn    server.hostname    localhost
```

**Comment by xenithorb** [comment]
Indeed you are correct, and I've had the fix here for a little while. I've been extremely busy, and I need to be more diligent about pushing code to master:

 https://github.com/RocketChat/Rocket.Chat.Ansible/commit/fb315afbd4b645bee79b7368317910133c99b49d#diff-2444ad0870f91f17ca6c2a5e96b26823R118 

There are quite a few updates contained in that branch. You're welcomed to test it (that branch) if you want.

**Comment by jautz** [comment]
Allow me to add a few suggestions from our code base that currently has this as a workaround:
- the regexp could be a bit more precise, i.e. escape the literal dots and require any kind of whitespace after the final digit -- otherwise it would match 127.0.0.123 as well.
- if missing, insert on top of the hosts file because on many systems it is IPv4 on top and IPv6 below.

```
- lineinfile:
    dest: /etc/hosts
    line:  "127.0.0.1\tlocalhost\t{{ ansible_fqdn }}\t{{ ansible_nodename }}\t{{ ansible_hostname }}"
    regexp: '^127\.0\.0\.1\s+'
    insertbefore: BOF
```
