### ISSUE TITLE
optional smtp server installation?

### ISSUE THREAD

**Issue by taybin** [RocketChat/Rocket.Chat.Ansible#6]
Does it make sense to include an optional smtp server to prevent issues like https://github.com/RocketChat/Rocket.Chat/issues/766 from happening?

**Comment by cmacrae** [comment]
Hey again @taybin :)

This is out of the scope of this role's intended functionality.
Ansible roles are something that users can, and are urged to, couple together.

Providing the ability to provision an SMTP server using this role would be something I'd consider irresponsible on my part as it's not encompassed in what I would consider Rocket.Chat's bare minimum requirements.

Those using this role should be familiar with Ansible and its capabilities. Although the deployment document for the use of this role is aimed at users unfamiliar with Ansible, it should cater as an example of what can be achieved and thus push users to explore and learn infrastructure definition/deployment using Ansible.

Deploying an SMTP server in addition to using this role with a playbook (as it should be done) would be as easy as something like:
``` yaml
- hosts: chat_servers
  roles:
    - RocketChat.Server
    - some_smtp_role
```

Or even just as raw tasks, if you can't find an SMTP role you want to use:
``` yaml
- hosts: chat_servers
  roles:
    - RocketChat.Server

  post_tasks:
    - name: Ensure postfix is present
       package: name=postfix state=present

   - name: Deploy postfix configuration
     template:
      src: postfix_config.j2
      dest: /some/path/postfix.conf

   - name: Ensure postfix service is started/enabled
      service: name=postfix state=started enabled=true
```
The above is purely loose examples that I just wrote down off the top of my head to convey my reasoning behind not including an SMTP server, so, don't expect it to work!

Ansible roles should be considered modular, and should be used as building blocks to deploy your services. Some situations may only require one role, others could require a few or many.
