### ISSUE TITLE
Centos7: current version needs develop branch to upgrade/install

### ISSUE THREAD

**Issue by arnehueggenberg** [RocketChat/Rocket.Chat.Ansible#63]
In order to get  Rocketchast to upgrade to the current (0.60.2) version  i had to clone the develop branch and override some variables. 

OS: Centos 7
```

- name: rocketchat install
  hosts: xxx.xxx.xxx
  tags: rocketchat
  roles:
    - { role: Rocket.Chat.Ansible, become: true }

  vars:
    rocket_chat_tarball_remote: https://releases.rocket.chat/latest/download
    rocket_chat_automatic_upgrades: true
    rocket_chat_tarball_sha256sum: "54e61a493a7c038859408e6d0caf2b34324edf1371a3946198c24869316c06b0."
    rocket_chat_node_version: 8.9.4
    rocket_chat_npm_version: 5.6.0
```
