### ISSUE TITLE
Enhancement: Support ADMIN_USERNAME and ADMIN_PASS role variables

### ISSUE THREAD

**Issue by nickbroon** [RocketChat/Rocket.Chat.Ansible#67]
https://rocket.chat/docs/administrator-guides/create-the-first-admin/
It would be very useful to be able to create the admin account during deployment.

**Comment by nickbroon** [comment]
Better yet would be support for controlling all RocketChat setting from the environment.
Something like:

```
- hosts: rocketchat_servers
  become: yes
  environment:
    OVERWRITE_SETTING_Site_Name: "foobar_my_site"
    OVERWRITE_SETTING_CROWD_Enable: "true"
    #OVERWRITE_SETTING_ any other setting
  roles:
  - RocketChat.Server
```

This would allow for having full control of the settings from the Ansible deployment.

There is details of these environment variables here https://github.com/RocketChat/docs/issues/261

But appears these are not making from the Ansible environment declaration through to the rocketchat service that's started up.

**Comment by xenithorb** [comment]
I believe the reason they're not being passed is due to the use of `become:` before we install the contents of the rocket.chat tarball with `npm`. Effectively what is happening is that `sudo`, which ansible is using in order to `become:` sanitizes the environment.

**Comment by xenithorb** [comment]
This actually doesn't pan out the way I thought it did...

A test such as this:

```yaml
---

- hosts: all

  tasks:

       - name: Test sudo environment
         shell: |
             whoami
             export | grep THIS_IS_A
         environment:
             THIS_IS_A_TEST: foo

       - name: Test sudo environment
         shell: |
             whoami
             export | grep THIS_IS_A
         environment:
             THIS_IS_A_TEST: foo
         become: yes
```

Proves the opposite with the output:

```
export SUDO_COMMAND="/bin/sh -c echo BECOME-SUCCESS-ksdkvtmohofqklnfntlxcazqmrktjjtj; THIS_IS_A_TEST=foo /usr/bin/python /home/xenith/.ansible/tmp/ansible-tmp-1519743231.01-111888138306384/command.py; rm -rf \"/home/xenith/.ansible/tmp/ansible-tmp-1519743231.01-111888138306384/\" > /dev/null 2>&1"
export THIS_IS_A_TEST="foo"

```
So, it does in fact look like ansible is "doing the right thing" here and passing along the environment variables. 

My thoughts on this now is that we might be able to get away with introducing a variable `{{ rocket_chat_environment }}` that would take a dictionary 

```yaml
---

- hosts: all

  vars:
    rocket_chat_environment:
        THIS_IS_A_TEST: foo
        THIS_IS_ANOTHER_TEST: bar

  tasks:

       - name: Test sudo environment
         shell: |
             whoami
             export | grep THIS_IS_A
         environment: "{{ rocket_chat_environment | default('{}') }}"
         become: yes
```

Output: 

```
STDOUT:

root
export SUDO_COMMAND="/bin/sh -c echo BECOME-SUCCESS-vhxnixwidttsthwbarvtjcshbqmrmicl; THIS_IS_A_TEST=foo THIS_IS_ANOTHER_TEST=bar /usr/bin/python /home/xenith/.ansible/tmp/ansible-tmp-1519743586.03-14652642632758/command.py; rm -rf \"/home/xenith/.ansible/tmp/ansible-tmp-1519743586.03-14652642632758/\" > /dev/null 2>&1"
export THIS_IS_ANOTHER_TEST="bar"
export THIS_IS_A_TEST="foo"
```

**Comment by nickbroon** [comment]
I think the problem is that rocketchat is started as a systemd init service, that by default will not pick these up. So I think these variables would need to be injected into the rocketchat.service.j2 template as Environment variables along side those already there.

**Comment by xenithorb** [comment]
Ah, I wasn't tracking where you wanted them until now. I had thought you wanted them available during the application install. 

Yeah, putting them in the service file is just a matter of templating that. Easy stuff. 


Just so we're clear:

```yaml
- hosts: rocketchat_servers
  become: yes

  vars:
    rocket_chat_environment:
      OVERWRITE_SETTING_Site_Name: "foobar_my_site"
      OVERWRITE_SETTING_CROWD_Enable: "true"
      #OVERWRITE_SETTING_ any other setting

  roles:
  - RocketChat.Server
```
Which results in...

```
# /usr/lib/systemd/system/rocketchat.service
[Unit]
Description=Rocket.Chat Server
After=syslog.target
After=network.target

[Service]
Type=simple
Restart=always
StandardOutput=syslog
SyslogIdentifier=RocketChat
User=rocketchat
Group=rocketchat
Environment=MONGO_URL=mongodb://127.0.0.1:27017/rocketchat
Environment=MONGO_OPLOG_URL=mongodb://127.0.0.1:27017/local
Environment=ROOT_URL=https://chat.opsech.io
Environment=PORT=3000
Environment=OVERWRITE_SETTING_Site_Name="foobar_my_site"
Environment=OVERWRITE_SETTING_CROWD_Enable="true"
WorkingDirectory=/var/lib/rocket.chat
ExecStart=/usr/local/n/versions/node/8.9.4/bin/node /var/lib/rocket.chat/bundle/main.js

[Install]
WantedBy=multi-user.target
```

Would work for you? (I don't use the ENV variables myself)
