### ISSUE TITLE
{"msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}

### ISSUE THREAD

**Issue by rodrigorodriguescosta** [RocketChat/Rocket.Chat.Ansible#99]
This issue occur when I try to install

my playbook

---
- hosts: rocketchat
  become: true

  vars:
    rocket_chat_automatic_upgrades: true
    rocket_chat_include_mongodb: false
    rocket_chat_mongodb_server: 192.168.0.1
    ansible_python_interpreter: "/usr/bin/python3"

  roles:
    - RocketChat.Server
```

**Comment by tumainimosha** [comment]
Same issue here. Installing on ubuntu 18.04 and ansible 2.8.1

```
No file was found when using first_found. Use the 'skip: true' option 
```

**Comment by barm0leykin** [comment]
The problem all is still actual. Ubuntu 18.04, ansible 2.8.2

**Comment by lossos** [comment]
The latest release of the Role here and on Galaxy is from Feb 2018. As workaround till RocketChat issues a new release, you can clone this repo.

**Comment by patsevanton** [comment]
Same error

Install
```
ansible-galaxy install --force git+https://github.com/RocketChat/Rocket.Chat.Ansible.git,develop
```
Run
```
ansible-playbook -i inventory.yml playbook.yml
```

Playbook
```
  - hosts: rocketchat
    become: true
    roles:
      - Rocket.Chat.Ansible
```

Inventory
```
all:
  children:
    rocketchat:
      hosts:
        "rocketchat":
          ansible_host: "xxxxx"
  vars:
    ansible_user:  ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

```

Version
```
ansible [core 2.12.2]
  python version = 3.8.10 (default, Nov 26 2021, 20:14:08) [GCC 9.3.0]
```

Server where ansible
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```

Remote server
```
cat /etc/*release*
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
```
